[package]
name = "srs-poly"
version = "0.1.0"
edition = "2021"
description = "utilities for polynomial systems"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }