[package]
name = "srs_solver"
version = "0.1.0"
edition = "2021"
description = "the constraint solver for the Sirius type checker"

[dev-dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }